<?php
if ( function_exists( 'acf_add_local_field_group' ) ):

    acf_add_local_field_group( array(
        'key'                   => 'group_63dd005b0f1dd',
        'title'                 => 'Category slider',
        'fields'                => array(
            array(
                'key'        => 'field_63dd005b18780',
                'label'      => 'Slider Heading',
                'name'       => 'shopx_cat_slider_heading',
                'aria-label' => '',
                'type'       => 'text',

            ),
            array(
                'key'        => 'field_63dd00b418781',
                'label'      => 'Slider box 1',
                'name'       => 'shopx_cat_slider_slider_box_1',
                'aria-label' => '',
                'type'       => 'group',
                'layout'     => 'block',
                'sub_fields' => array(
                    array(
                        'key'               => 'field_63dd00ca18782',
                        'label'             => 'Slider Box icon',
                        'name'              => 'slider_box_1_icon',
                        'aria-label'        => '',
                        'type'              => 'image',
                        'instructions'      => '',
                        'required'          => 0,
                        'conditional_logic' => 0,
                        'wrapper'           => array(
                            'width' => '',
                            'class' => '',
                            'id'    => '',
                        ),
                        'return_format'     => 'array',
                        'library'           => 'all',
                        'min_width'         => '',
                        'min_height'        => '',
                        'min_size'          => '',
                        'max_width'         => '',
                        'max_height'        => '',
                        'max_size'          => '',
                        'mime_types'        => '',
                        'preview_size'      => 'medium',
                    ),
                    array(
                        'key'               => 'field_63dd01e018783',
                        'label'             => 'Slider Box Name',
                        'name'              => 'slider_box_name',
                        'aria-label'        => '',
                        'type'              => 'text',
                        'instructions'      => '',
                        'required'          => 0,
                        'conditional_logic' => 0,
                        'wrapper'           => array(
                            'width' => '',
                            'class' => '',
                            'id'    => '',
                        ),
                        'default_value'     => '',
                        'maxlength'         => '',
                        'placeholder'       => '',
                        'prepend'           => '',
                        'append'            => '',
                    ),
                    array(
                        'key'               => 'field_63dd021f18784',
                        'label'             => 'Slider Box Url',
                        'name'              => 'slider_box_url',
                        'aria-label'        => '',
                        'type'              => 'url',
                        'instructions'      => '',
                        'required'          => 0,
                        'conditional_logic' => 0,
                        'wrapper'           => array(
                            'width' => '',
                            'class' => '',
                            'id'    => '',
                        ),
                        'default_value'     => '',
                        'placeholder'       => '',
                    ),
                ),
            ),
            array(
                'key'               => 'field_63dd0be883dc5',
                'label'             => 'Slider box 2',
                'name'              => 'shopx_cat_slider_slider_box_2',
                'aria-label'        => '',
                'type'              => 'group',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'layout'            => 'block',
                'sub_fields'        => array(
                    array(
                        'key'               => 'field_63dd0be883dc6',
                        'label'             => 'Slider Box icon',
                        'name'              => 'slider_box_1_icon',
                        'aria-label'        => '',
                        'type'              => 'image',
                        'instructions'      => '',
                        'required'          => 0,
                        'conditional_logic' => 0,
                        'wrapper'           => array(
                            'width' => '',
                            'class' => '',
                            'id'    => '',
                        ),
                        'return_format'     => '',
                        'library'           => '',
                        'min_width'         => '',
                        'min_height'        => '',
                        'min_size'          => '',
                        'max_width'         => '',
                        'max_height'        => '',
                        'max_size'          => '',
                        'mime_types'        => '',
                        'preview_size'      => 'medium',
                    ),
                    array(
                        'key'               => 'field_63dd0be883dc7',
                        'label'             => 'Slider Box Name',
                        'name'              => 'slider_box_name',
                        'aria-label'        => '',
                        'type'              => 'text',
                        'instructions'      => '',
                        'required'          => 0,
                        'conditional_logic' => 0,
                        'wrapper'           => array(
                            'width' => '',
                            'class' => '',
                            'id'    => '',
                        ),
                        'default_value'     => '',
                        'maxlength'         => '',
                        'placeholder'       => '',
                        'prepend'           => '',
                        'append'            => '',
                    ),
                    array(
                        'key'               => 'field_63dd0be883dc8',
                        'label'             => 'Slider Box Url',
                        'name'              => 'slider_box_url',
                        'aria-label'        => '',
                        'type'              => 'url',
                        'instructions'      => '',
                        'required'          => 0,
                        'conditional_logic' => 0,
                        'wrapper'           => array(
                            'width' => '',
                            'class' => '',
                            'id'    => '',
                        ),
                        'default_value'     => '',
                        'placeholder'       => '',
                    ),
                ),
            ),
            array(
                'key'               => 'field_63dd0be983dc9',
                'label'             => 'Slider box 3',
                'name'              => 'shopx_cat_slider_slider_box_3',
                'aria-label'        => '',
                'type'              => 'group',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'layout'            => 'block',
                'sub_fields'        => array(
                    array(
                        'key'               => 'field_63dd0be983dca',
                        'label'             => 'Slider Box icon',
                        'name'              => 'slider_box_1_icon',
                        'aria-label'        => '',
                        'type'              => 'image',
                        'instructions'      => '',
                        'required'          => 0,
                        'conditional_logic' => 0,
                        'wrapper'           => array(
                            'width' => '',
                            'class' => '',
                            'id'    => '',
                        ),
                        'return_format'     => '',
                        'library'           => '',
                        'min_width'         => '',
                        'min_height'        => '',
                        'min_size'          => '',
                        'max_width'         => '',
                        'max_height'        => '',
                        'max_size'          => '',
                        'mime_types'        => '',
                        'preview_size'      => 'medium',
                    ),
                    array(
                        'key'               => 'field_63dd0be983dcb',
                        'label'             => 'Slider Box Name',
                        'name'              => 'slider_box_name',
                        'aria-label'        => '',
                        'type'              => 'text',
                        'instructions'      => '',
                        'required'          => 0,
                        'conditional_logic' => 0,
                        'wrapper'           => array(
                            'width' => '',
                            'class' => '',
                            'id'    => '',
                        ),
                        'default_value'     => '',
                        'maxlength'         => '',
                        'placeholder'       => '',
                        'prepend'           => '',
                        'append'            => '',
                    ),
                    array(
                        'key'               => 'field_63dd0be983dcc',
                        'label'             => 'Slider Box Url',
                        'name'              => 'slider_box_url',
                        'aria-label'        => '',
                        'type'              => 'url',
                        'instructions'      => '',
                        'required'          => 0,
                        'conditional_logic' => 0,
                        'wrapper'           => array(
                            'width' => '',
                            'class' => '',
                            'id'    => '',
                        ),
                        'default_value'     => '',
                        'placeholder'       => '',
                    ),
                ),
            ),
            array(
                'key'               => 'field_63dd0bec83dcd',
                'label'             => 'Slider box 4',
                'name'              => 'shopx_cat_slider_slider_box_4',
                'aria-label'        => '',
                'type'              => 'group',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'layout'            => 'block',
                'sub_fields'        => array(
                    array(
                        'key'               => 'field_63dd0bec83dce',
                        'label'             => 'Slider Box icon',
                        'name'              => 'slider_box_1_icon',
                        'aria-label'        => '',
                        'type'              => 'image',
                        'instructions'      => '',
                        'required'          => 0,
                        'conditional_logic' => 0,
                        'wrapper'           => array(
                            'width' => '',
                            'class' => '',
                            'id'    => '',
                        ),
                        'return_format'     => '',
                        'library'           => '',
                        'min_width'         => '',
                        'min_height'        => '',
                        'min_size'          => '',
                        'max_width'         => '',
                        'max_height'        => '',
                        'max_size'          => '',
                        'mime_types'        => '',
                        'preview_size'      => 'medium',
                    ),
                    array(
                        'key'               => 'field_63dd0bec83dcf',
                        'label'             => 'Slider Box Name',
                        'name'              => 'slider_box_name',
                        'aria-label'        => '',
                        'type'              => 'text',
                        'instructions'      => '',
                        'required'          => 0,
                        'conditional_logic' => 0,
                        'wrapper'           => array(
                            'width' => '',
                            'class' => '',
                            'id'    => '',
                        ),
                        'default_value'     => '',
                        'maxlength'         => '',
                        'placeholder'       => '',
                        'prepend'           => '',
                        'append'            => '',
                    ),
                    array(
                        'key'               => 'field_63dd0bec83dd0',
                        'label'             => 'Slider Box Url',
                        'name'              => 'slider_box_url',
                        'aria-label'        => '',
                        'type'              => 'url',
                        'instructions'      => '',
                        'required'          => 0,
                        'conditional_logic' => 0,
                        'wrapper'           => array(
                            'width' => '',
                            'class' => '',
                            'id'    => '',
                        ),
                        'default_value'     => '',
                        'placeholder'       => '',
                    ),
                ),
            ),
            array(
                'key'               => 'field_63dd0bed83dd1',
                'label'             => 'Slider box 5',
                'name'              => 'shopx_cat_slider_slider_box_5',
                'aria-label'        => '',
                'type'              => 'group',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'layout'            => 'block',
                'sub_fields'        => array(
                    array(
                        'key'               => 'field_63dd0bed83dd2',
                        'label'             => 'Slider Box icon',
                        'name'              => 'slider_box_1_icon',
                        'aria-label'        => '',
                        'type'              => 'image',
                        'instructions'      => '',
                        'required'          => 0,
                        'conditional_logic' => 0,
                        'wrapper'           => array(
                            'width' => '',
                            'class' => '',
                            'id'    => '',
                        ),
                        'return_format'     => '',
                        'library'           => '',
                        'min_width'         => '',
                        'min_height'        => '',
                        'min_size'          => '',
                        'max_width'         => '',
                        'max_height'        => '',
                        'max_size'          => '',
                        'mime_types'        => '',
                        'preview_size'      => 'medium',
                    ),
                    array(
                        'key'               => 'field_63dd0bed83dd3',
                        'label'             => 'Slider Box Name',
                        'name'              => 'slider_box_name',
                        'aria-label'        => '',
                        'type'              => 'text',
                        'instructions'      => '',
                        'required'          => 0,
                        'conditional_logic' => 0,
                        'wrapper'           => array(
                            'width' => '',
                            'class' => '',
                            'id'    => '',
                        ),
                        'default_value'     => '',
                        'maxlength'         => '',
                        'placeholder'       => '',
                        'prepend'           => '',
                        'append'            => '',
                    ),
                    array(
                        'key'               => 'field_63dd0bed83dd4',
                        'label'             => 'Slider Box Url',
                        'name'              => 'slider_box_url',
                        'aria-label'        => '',
                        'type'              => 'url',
                        'instructions'      => '',
                        'required'          => 0,
                        'conditional_logic' => 0,
                        'wrapper'           => array(
                            'width' => '',
                            'class' => '',
                            'id'    => '',
                        ),
                        'default_value'     => '',
                        'placeholder'       => '',
                    ),
                ),
            ),
            array(
                'key'               => 'field_63dd0bef83dd5',
                'label'             => 'Slider box 6',
                'name'              => 'shopx_cat_slider_slider_box_6',
                'aria-label'        => '',
                'type'              => 'group',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'layout'            => 'block',
                'sub_fields'        => array(
                    array(
                        'key'               => 'field_63dd0bef83dd6',
                        'label'             => 'Slider Box icon',
                        'name'              => 'slider_box_1_icon',
                        'aria-label'        => '',
                        'type'              => 'image',
                        'instructions'      => '',
                        'required'          => 0,
                        'conditional_logic' => 0,
                        'wrapper'           => array(
                            'width' => '',
                            'class' => '',
                            'id'    => '',
                        ),
                        'return_format'     => 'array',
                        'library'           => 'all',
                        'min_width'         => '',
                        'min_height'        => '',
                        'min_size'          => '',
                        'max_width'         => '',
                        'max_height'        => '',
                        'max_size'          => '',
                        'mime_types'        => '',
                        'preview_size'      => 'medium',
                    ),
                    array(
                        'key'               => 'field_63dd0bef83dd7',
                        'label'             => 'Slider Box Name',
                        'name'              => 'slider_box_name',
                        'aria-label'        => '',
                        'type'              => 'text',
                        'instructions'      => '',
                        'required'          => 0,
                        'conditional_logic' => 0,
                        'wrapper'           => array(
                            'width' => '',
                            'class' => '',
                            'id'    => '',
                        ),
                        'default_value'     => '',
                        'maxlength'         => '',
                        'placeholder'       => '',
                        'prepend'           => '',
                        'append'            => '',
                    ),
                    array(
                        'key'               => 'field_63dd0bef83dd8',
                        'label'             => 'Slider Box Url',
                        'name'              => 'slider_box_url',
                        'aria-label'        => '',
                        'type'              => 'url',
                        'instructions'      => '',
                        'required'          => 0,
                        'conditional_logic' => 0,
                        'wrapper'           => array(
                            'width' => '',
                            'class' => '',
                            'id'    => '',
                        ),
                        'default_value'     => '',
                        'placeholder'       => '',
                    ),
                ),
            ),
            array(
                'key'               => 'field_63dd0aaa1a244',
                'label'             => 'SLider Box Link',
                'name'              => 'shopx_cat_slider_box_link',
                'aria-label'        => '',
                'type'              => 'url',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'placeholder'       => '',
            ),
        ),
        'location'              => array(
            array(
                array(
                    'param'    => 'post_type',
                    'operator' => '==',
                    'value'    => 'categoryslider',
                ),
            ),
        ),
        'menu_order'            => 0,
        'position'              => 'normal',
        'style'                 => 'default',
        'label_placement'       => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen'        => '',
        'active'                => true,
        'description'           => '',
        'show_in_rest'          => 0,
    ) );

endif;